# Config for https://github.com/apps/release-drafter
name-template: 'v$NEXT_MINOR_VERSION (🌈 Insert Release Name)'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'Dependency Updates'
    label: 'dependencies'
template: |
  $CHANGES

  ## Upgrading

  To upgrade, update your `pipeline.yml` files:

  ```diff
  steps:
    - command: test.sh
      plugins:
  -     test-collector#$PREVIOUS_TAG:
  +     test-collector#v$NEXT_MINOR_VERSION:
          files: "test/junit-*.xml"
          format: "junit"
  ```
